### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/brms-weightwatcher-realtime-decision-server-demo#10]
From the field:

"I was following your demo of weightwatcher ( https://github.com/jbossdemocentral/brms-weightwatcher-realtime-decision-server-demo ). But i found that a header was missing when doing the request. 
If i query the server with the parameters you describe: authorization and content-type, the response from the server is not OK. I had to add X-KIE-ContentType : xstream, as in the brms-loan-realtime-decision-server-demo, and i get the correct response."

**Comment by DuncanDoyle** [comment]
Ohw, that one again ..... They should make a missing header default to "xstream" .... Will fix ASAP.

**Comment by DuncanDoyle** [comment]
First needed to upgrade to BRMS 6.3.0.GA and fix Docker deployments, see #11.
