### ISSUE TITLE
Documentation contains obsolete tasks

### ISSUE THREAD

**Issue by PatrickSteiner** [jbossdemocentral/brms-weightwatcher-realtime-decision-server-demo#3]
When doing a fresh install, steps 8 and 9 are already done, so they should be removed from the documentation to not create any confusion.

**Comment by eschabell** [comment]
Fixed in https://github.com/jbossdemocentral/brms-weightwatcher-realtime-decision-server-demo/commit/40064a3204b65ef2c083643c0abf7286edba3004
