### ISSUE TITLE
Loans?

### ISSUE THREAD

**Issue by PatrickSteiner** [jbossdemocentral/brms-weightwatcher-realtime-decision-server-demo#4]
Documentation starts to talk about querying "loan rules" in section 16?

Also following the steps 15 & 16 results in 

<response type="FAILURE" msg="Error calling container container-weightwatchers1.0: java.lang.RuntimeException: Query 'getWatch' does not exist"/>

**Comment by eschabell** [comment]
Fixed in https://github.com/jbossdemocentral/brms-weightwatcher-realtime-decision-server-demo/commit/da124575fa1cf7d1ac1b934b0de24107e6071e40
