### ISSUE TITLE
Step 9. weightwatchers doesnt show on search list

### ISSUE THREAD

**Issue by hodrigohamalho** [jbossdemocentral/brms-weightwatcher-realtime-decision-server-demo#6]
On step 9:

```
9. Provision starts by creating a Container, click on DevServer '+' on right.

Name: container-weightwatchers1.0

search button gathers all artifacts available, SELECT weightwatchers-1.0 to auto-fill rest of fields
```

The weightwatchers is not showed as an option to select.

**Comment by hodrigohamalho** [comment]
The project seems to need be installed on maven local repository...

**Comment by eschabell** [comment]
Yes, that is part of the initial install script check, no maven, install stops. When you start the server, you first need to build & deploy the project, this will then put it into the options to select.

**Comment by hodrigohamalho** [comment]
Yeah, it worked here. 
This information is very helpful. It should be on README file.

Thank you!
